const tree = require('decision-tree');
const AppError = require('./../utils/appError');
const catchAsync = require('./../utils/catchAsync');

const trainingData = [
  {
    'thể thao': 1,
    'ẩm thực': 0,
    'thời trang': 0,
    'giao tiếp': 0,
    'phim ảnh': 0,
    'trò chơi': 0,
    label: 'thể thao',
  },
  {
    'thể thao': 0,
    'ẩm thực': 1,
    'thời trang': 0,
    'giao tiếp': 0,
    'phim ảnh': 0,
    'trò chơi': 0,
    label: 'ẩm thực',
  },
  {
    'thể thao': 0,
    'ẩm thực': 0,
    'thời trang': 1,
    'giao tiếp': 0,
    'phim ảnh': 0,
    'trò chơi': 0,
    label: 'thời trang',
  },
  {
    'thể thao': 0,
    'ẩm thực': 0,
    'thời trang': 0,
    'giao tiếp': 1,
    'phim ảnh': 0,
    'trò chơi': 0,
    label: 'giao tiếp',
  },
  {
    'thể thao': 0,
    'ẩm thực': 0,
    'thời trang': 0,
    'giao tiếp': 0,
    'phim ảnh': 1,
    'trò chơi': 0,
    label: 'phim ảnh',
  },
  {
    'thể thao': 1,
    'ẩm thực': 1,
    'thời trang': 0,
    'giao tiếp': 0,
    'phim ảnh': 0,
    'trò chơi': 0,
    label: 'thể thao',
  },
  {
    'thể thao': 1,
    'ẩm thực': 0,
    'thời trang': 1,
    'giao tiếp': 0,
    'phim ảnh': 0,
    'trò chơi': 0,
    label: 'thể thao',
  },
  {
    'thể thao': 1,
    'ẩm thực': 0,
    'thời trang': 0,
    'giao tiếp': 1,
    'phim ảnh': 0,
    'trò chơi': 0,
    label: 'thể thao',
  },
  {
    'thể thao': 0,
    'ẩm thực': 1,
    'thời trang': 1,
    'giao tiếp': 0,
    'phim ảnh': 0,
    'trò chơi': 0,
    label: 'ẩm thực',
  },
  {
    'thể thao': 0,
    'ẩm thực': 1,
    'thời trang': 0,
    'giao tiếp': 1,
    'phim ảnh': 0,
    'trò chơi': 0,
    label: 'ẩm thực',
  },
  {
    'thể thao': 0,
    'ẩm thực': 0,
    'thời trang': 1,
    'giao tiếp': 1,
    'phim ảnh': 0,
    'trò chơi': 0,
    label: 'thời trang',
  },
  {
    'thể thao': 1,
    'ẩm thực': 1,
    'thời trang': 1,
    'giao tiếp': 0,
    'phim ảnh': 0,
    'trò chơi': 0,
    label: 'thể thao',
  },
  {
    'thể thao': 1,
    'ẩm thực': 0,
    'thời trang': 1,
    'giao tiếp': 1,
    'phim ảnh': 0,
    'trò chơi': 0,
    label: 'thể thao',
  },
  {
    'thể thao': 1,
    'ẩm thực': 0,
    'thời trang': 0,
    'giao tiếp': 1,
    'phim ảnh': 1,
    'trò chơi': 0,
    label: 'thể thao',
  },
  {
    'thể thao': 0,
    'ẩm thực': 1,
    'thời trang': 1,
    'giao tiếp': 1,
    'phim ảnh': 0,
    'trò chơi': 0,
    label: 'ẩm thực',
  },
  {
    'thể thao': 0,
    'ẩm thực': 1,
    'thời trang': 0,
    'giao tiếp': 1,
    'phim ảnh': 1,
    'trò chơi': 0,
    label: 'ẩm thực',
  },
  {
    'thể thao': 0,
    'ẩm thực': 0,
    'thời trang': 1,
    'giao tiếp': 1,
    'phim ảnh': 1,
    'trò chơi': 0,
    label: 'thời trang',
  },
  {
    'thể thao': 1,
    'ẩm thực': 1,
    'thời trang': 1,
    'giao tiếp': 1,
    'phim ảnh': 0,
    'trò chơi': 0,
    label: 'thể thao',
  },
  {
    'thể thao': 1,
    'ẩm thực': 1,
    'thời trang': 0,
    'giao tiếp': 1,
    'phim ảnh': 1,
    'trò chơi': 0,
    label: 'thể thao',
  },
  {
    'thể thao': 1,
    'ẩm thực': 0,
    'thời trang': 1,
    'giao tiếp': 1,
    'phim ảnh': 1,
    'trò chơi': 0,
    label: 'thể thao',
  },
  {
    'thể thao': 0,
    'ẩm thực': 1,
    'thời trang': 1,
    'giao tiếp': 1,
    'phim ảnh': 1,
    'trò chơi': 0,
    label: 'ẩm thực',
  },
  {
    'thể thao': 1,
    'ẩm thực': 1,
    'thời trang': 1,
    'giao tiếp': 1,
    'phim ảnh': 1,
    'trò chơi': 0,
    label: 'thể thao',
  },
  {
    'thể thao': 1,
    'ẩm thực': 1,
    'thời trang': 1,
    'giao tiếp': 1,
    'phim ảnh': 1,
    'trò chơi': 1,
    label: 'thể thao',
  },
  {
    'thể thao': 1,
    'ẩm thực': 0,
    'thời trang': 0,
    'giao tiếp': 0,
    'phim ảnh': 0,
    'trò chơi': 1,
    label: 'thể thao',
  },
  {
    'thể thao': 0,
    'ẩm thực': 1,
    'thời trang': 0,
    'giao tiếp': 0,
    'phim ảnh': 0,
    'trò chơi': 1,
    label: 'ẩm thực',
  },
  {
    'thể thao': 0,
    'ẩm thực': 0,
    'thời trang': 1,
    'giao tiếp': 0,
    'phim ảnh': 0,
    'trò chơi': 1,
    label: 'thời trang',
  },
  {
    'thể thao': 0,
    'ẩm thực': 0,
    'thời trang': 0,
    'giao tiếp': 1,
    'phim ảnh': 0,
    'trò chơi': 1,
    label: 'giao tiếp',
  },
  {
    'thể thao': 0,
    'ẩm thực': 0,
    'thời trang': 0,
    'giao tiếp': 0,
    'phim ảnh': 1,
    'trò chơi': 1,
    label: 'phim ảnh',
  },
  {
    'thể thao': 1,
    'ẩm thực': 1,
    'thời trang': 0,
    'giao tiếp': 0,
    'phim ảnh': 1,
    'trò chơi': 1,
    label: 'thể thao',
  },
  {
    'thể thao': 1,
    'ẩm thực': 0,
    'thời trang': 1,
    'giao tiếp': 0,
    'phim ảnh': 1,
    'trò chơi': 1,
    label: 'thể thao',
  },
  {
    'thể thao': 1,
    'ẩm thực': 0,
    'thời trang': 0,
    'giao tiếp': 1,
    'phim ảnh': 1,
    'trò chơi': 1,
    label: 'thể thao',
  },
  {
    'thể thao': 0,
    'ẩm thực': 1,
    'thời trang': 1,
    'giao tiếp': 0,
    'phim ảnh': 1,
    'trò chơi': 1,
    label: 'ẩm thực',
  },
  {
    'thể thao': 0,
    'ẩm thực': 1,
    'thời trang': 0,
    'giao tiếp': 1,
    'phim ảnh': 1,
    'trò chơi': 1,
    label: 'ẩm thực',
  },
  {
    'thể thao': 0,
    'ẩm thực': 0,
    'thời trang': 1,
    'giao tiếp': 1,
    'phim ảnh': 1,
    'trò chơi': 1,
    label: 'thời trang',
  },
  {
    'thể thao': 1,
    'ẩm thực': 1,
    'thời trang': 1,
    'giao tiếp': 0,
    'phim ảnh': 1,
    'trò chơi': 1,
    label: 'thể thao',
  },
  {
    'thể thao': 1,
    'ẩm thực': 1,
    'thời trang': 0,
    'giao tiếp': 1,
    'phim ảnh': 1,
    'trò chơi': 1,
    label: 'thể thao',
  },
  {
    'thể thao': 1,
    'ẩm thực': 0,
    'thời trang': 1,
    'giao tiếp': 1,
    'phim ảnh': 1,
    'trò chơi': 1,
    label: 'thể thao',
  },
  {
    'thể thao': 0,
    'ẩm thực': 1,
    'thời trang': 1,
    'giao tiếp': 1,
    'phim ảnh': 1,
    'trò chơi': 1,
    label: 'ẩm thực',
  },
  {
    'thể thao': 1,
    'ẩm thực': 1,
    'thời trang': 1,
    'giao tiếp': 1,
    'phim ảnh': 1,
    'trò chơi': 1,
    label: 'thể thao',
  },

  // Thêm dữ liệu huấn luyện khác tương tự

  ,
];
const target = 'label';
const features = [
  'thể thao',
  'ẩm thực',
  'thời trang',
  'giao tiếp',
  'phim ảnh',
  'trò chơi',
];
exports.ChudeGoiY = catchAsync(async (req, res, next) => {
  const dt = new tree(trainingData, target, features);
  const pre = dt.predict(req.body);
  res.status(200).json({
    status: 'success',
    data: pre,
  });
});
